name: flutter_yt_dlp
description: "A Flutter plugin for downloading and processing media using yt-dlp and FFmpeg."
version: 0.2.0
homepage: https://github.com/utoxas/flutter_yt_dlp

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_yt_dlp
        pluginClass: FlutterYtDlpPlugin